# Generated by Django 4.1.1 on 2022-09-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_item_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("Rub", "Рубли"), ("usd", "Доллары")],
                default="Rub",
                max_length=10,
                verbose_name="Валюта",
            ),
        ),
    ]
